import React from 'react';

const Disclaimer = () => {
  const disclaimer = [
    {
      section: 'Definitions and Key Terms',
      content:
        'In this Disclaimer, certain terms are strictly defined as follows:',
      terms: [
        {
          term: 'Cookie',
          definition:
            'A small data file generated by a website and stored by your web browser. It serves to identify your browser, provide analytics, and remember information such as language preference or login details.',
        },
        {
          term: 'Company',
          definition:
            "When this policy mentions 'Company,' 'we,' 'us,' or 'our,' it refers to our Store, which is responsible for your information under this Disclaimer.",
        },
      ],
    },
    {
      section: 'Limited Liability',
      content:
        "While our Store endeavors to regularly update and supplement the website's content, there may be instances where content is incomplete or inaccurate despite our efforts.",
      details: [
        'The materials provided on the website are offered without any guarantee or assertion of their accuracy. These materials are subject to change without prior notice from our Store.',
        'Specifically, all prices listed on the website are subject to typing and programming errors. Our Store assumes no liability for the consequences of such errors, and no agreement is formed based on them.',
        'Our Store shall not be held liable for hyperlinks to third-party websites included on our website. While we strive to provide quality links to reputable websites, we have no control over their content and nature. The inclusion of these links does not imply endorsement of all content found on those sites. Site ownership and content may change without notice, and this may occur before we can remove a link.',
      ],
    },
    {
      section: 'Not a Reseller of Any Brand',
      content:
        "At our Store, we specialize in acquiring pre-owned printers, scanners, laptops, and desktops for sale on our website. It's important to note that we operate as an independent seller and are not affiliated with any specific brands or manufacturers. Our focus is on delivering quality refurbished electronics to our customers without brand partnerships influencing our offerings.",
    },
    {
      section: 'Links to Other Websites Disclaimer',
      content:
        'Our Sites may contain links to other websites not under the control of our Store. We bear no responsibility for these linked websites, nor do these links constitute an endorsement of any linked pages. These links are provided solely for the convenience and information of our Site users.',
    },
    {
      section: 'Copyright Disclaimer',
      content:
        'All intellectual property rights pertaining to these materials are vested in our Store. Copying, distribution, or any other use of these materials is strictly prohibited without the written permission of our Store, except where otherwise provided by mandatory law (such as the right to quote).',
    },
    {
      section: 'Your Consent',
      content:
        "By using our website, registering an account, or making a purchase, you consent to our Disclaimer and agree to its terms. We've updated our Disclaimer to provide transparency regarding the data collected when you visit our site and how it's used.",
    },
    {
      section: 'Changes to Our Disclaimer',
      content:
        'If we update, amend, or modify this document to accurately reflect our website and policies, we will prominently post those changes here. By continuing to use the website after such changes, you agree to be bound by the updated Disclaimer. If you do not agree to this or any updated Disclaimer, you can delete your account.',
    },
  ];

  return (
    <div className="bg-gray-100 min-h-screen py-8">
      <div className="max-w-4xl mx-auto px-4">
        <h1 className="text-3xl font-bold mb-8 text-center">Disclaimer</h1>

        {disclaimer.map((item, index) => (
          <section key={index} className="mb-8">
            <h2 className="text-xl font-semibold mb-4">{item.section}</h2>
            <div className="bg-white p-4 rounded shadow">
              <p className="mb-4">{item.content}</p>
              {item.terms && (
                <ul className="list-disc ml-6 mb-4">
                  {item.terms.map((term, i) => (
                    <li key={i}>
                      <strong>{term.term}:</strong> {term.definition}
                    </li>
                  ))}
                </ul>
              )}
              {item.details && (
                <div className="mb-4">
                  {item.details.map((detail, i) => (
                    <p key={i} className="mb-2">
                      {detail}
                    </p>
                  ))}
                </div>
              )}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
};

export default Disclaimer;
